{
  'snp_file_dir' : '/scratch/hoeps/dltest',
  'path_to_sseq_bamdir' : '/g/korbel/hoeps/projects/strong-seq/data/strandseq',
  'path_to_longread_bamdir' : '/g/korbel/hoeps/projects/strong-seq/data/ont_data'
  'ref_fa' : '/g/korbel/hoeps/projects/huminvs/data/hg38/ref_chr_1_22XY.fa'
}
